### ISSUE TITLE
转移（Transfer ownership）本仓库到 guet1024？

### ISSUE THREAD

**Issue by lideming** [Telephone2019/CourseTable#186]

**Comment by TelephoneTan** [comment]
不懂，问题不大，目前这样挺好的

**Comment by lideming** [comment]
@Telephone2019
在仓库的 Settings 最底下有个 Transfer ownership（转移所有权），
转移到 guet1024 组织后，这个仓库的地址就会变成： https://github.com/guet1024/CourseTable
Issue 和 PR 都会保留，原地址 https://github.com/Telephone2019/CourseTable 会被自动跳转到新地址，
之后还可以在设置里把 CourseTable 这个仓库名字重命名成别的……

现在这样有两个仓库挺麻烦的，比如今天下午弹出的更新通知把我引导到了这个旧仓库的 releases 页面，返回主页才发现仓库迁移了。

**Comment by TelephoneTan** [comment]
谢谢你的反馈和详细的教程！很抱歉给你带来不好的体验。不过许多修改已经做出了......下次迁移仓库的时候我会使用你提到的方法的 😄

**Comment by lideming** [comment]
其实如果现在 transfer 到 guet1024 然后改名成 GUET-Schedule-Open 应该不会破坏什么东西……（当然，在这之前要把“新”仓库删除或重命名）
也不是很重要啦，只是感觉迁移的时候这么多 issues 之类的记录应该跟着过去……

**Comment by TelephoneTan** [comment]
嗯嗯，晚安 :D
